# Generated by Django 4.2 on 2025-08-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200000000)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('contact_name', models.CharField(max_length=2000000000)),
                ('contact_relation', models.CharField(choices=[('father', 'father'), ('mother', 'mother'), ('brother', 'brother'), ('sister', 'sister'), ('cousin', 'cousin'), ('guardian', 'guardian'), ('uncle', 'uncle'), ('aunt', 'aunt')], max_length=255)),
                ('contact_phone', models.PositiveBigIntegerField()),
            ],
        ),
    ]
